//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bortpad.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bortpad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _readonly {
            get {
                object obj = ResourceManager.GetObject("readonly", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string AssemblyCompany {
            get {
                return ResourceManager.GetString("AssemblyCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string AssemblyCopyright {
            get {
                return ResourceManager.GetString("AssemblyCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string AssemblyDescription {
            get {
                return ResourceManager.GetString("AssemblyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string AssemblyProduct {
            get {
                return ResourceManager.GetString("AssemblyProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string AssemblyTitle {
            get {
                return ResourceManager.GetString("AssemblyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string AssemblyVersion {
            get {
                return ResourceManager.GetString("AssemblyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon bortpad {
            get {
                object obj = ResourceManager.GetObject("bortpad", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bortpad1 {
            get {
                object obj = ResourceManager.GetObject("bortpad1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancelBtn_Text {
            get {
                return ResourceManager.GetString("cancelBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find &quot;{0}&quot;.
        /// </summary>
        public static string CannotFind {
            get {
                return ResourceManager.GetString("CannotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load any settings from configuration file..
        /// </summary>
        public static string CantLoadSettings {
            get {
                return ResourceManager.GetString("CantLoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you choose to edit this file, when you Save you will be prompted to either:
        ///• Unset the Read - Only flag
        ///• Save As a new document.
        /// </summary>
        public static string ChooseToEdit {
            get {
                return ResourceManager.GetString("ChooseToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Col.
        /// </summary>
        public static string Col {
            get {
                return ResourceManager.GetString("Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence: {0}%.
        /// </summary>
        public static string Confidence {
            get {
                return ResourceManager.GetString("Confidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.cfg.
        /// </summary>
        public static string ConfigFile {
            get {
                return ResourceManager.GetString("ConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert all End of Line characters in this document to {0}?.
        /// </summary>
        public static string ConvertLineEndings {
            get {
                return ResourceManager.GetString("ConvertLineEndings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any line endings in this document that are not already {0} will be converted to {0}.
        /// </summary>
        public static string ConvertLineEndingsDesc {
            get {
                return ResourceManager.GetString("ConvertLineEndingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string DefaultFilename {
            get {
                return ResourceManager.GetString("DefaultFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected.
        /// </summary>
        public static string Detected {
            get {
                return ResourceManager.GetString("Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do&amp;n&apos;t Save.
        /// </summary>
        public static string dontSaveBtn_Text {
            get {
                return ResourceManager.GetString("dontSaveBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        public static string editBtn_Text {
            get {
                return ResourceManager.GetString("editBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found next from the bottom.
        /// </summary>
        public static string FoundNextBottom {
            get {
                return ResourceManager.GetString("FoundNextBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found next from the top.
        /// </summary>
        public static string FoundNextTop {
            get {
                return ResourceManager.GetString("FoundNextTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Line.
        /// </summary>
        public static string GotoLine {
            get {
                return ResourceManager.GetString("GotoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid setting key provided..
        /// </summary>
        public static string InvalidSettingName {
            get {
                return ResourceManager.GetString("InvalidSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is marked as Read-Only.
        /// </summary>
        public static string IsMarkedAsReadOnly {
            get {
                return ResourceManager.GetString("IsMarkedAsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The line number is beyond the total number of lines.
        /// </summary>
        public static string LineNumberBeyond {
            get {
                return ResourceManager.GetString("LineNumberBeyond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ln.
        /// </summary>
        public static string Ln {
            get {
                return ResourceManager.GetString("Ln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap macos {
            get {
                object obj = ResourceManager.GetObject("macos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string okBtn_Text {
            get {
                return ResourceManager.GetString("okBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap os9 {
            get {
                object obj = ResourceManager.GetObject("os9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system cannot find the path specified..
        /// </summary>
        public static string PathNotFound {
            get {
                return ResourceManager.GetString("PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Save this file, either
        ///• Unset the Read - Only flag
        ///• Save As a new document.
        /// </summary>
        public static string ReadOnlyOptions {
            get {
                return ResourceManager.GetString("ReadOnlyOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap readonlyw {
            get {
                object obj = ResourceManager.GetObject("readonlyw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset configuration file to defaults?.
        /// </summary>
        public static string ResetConfigFile {
            get {
                return ResourceManager.GetString("ResetConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;As....
        /// </summary>
        public static string saveAsBtn_Text {
            get {
                return ResourceManager.GetString("saveAsBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        public static string saveBtn_Text {
            get {
                return ResourceManager.GetString("saveBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to {0}?.
        /// </summary>
        public static string SaveChangesTo {
            get {
                return ResourceManager.GetString("SaveChangesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap shift {
            get {
                object obj = ResourceManager.GetObject("shift", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Unset and Save.
        /// </summary>
        public static string unsetAndSaveBtn_Text {
            get {
                return ResourceManager.GetString("unsetAndSaveBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap windows {
            get {
                object obj = ResourceManager.GetObject("windows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
